name: ada_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0
  device_preview: ^1.2.0
  dropdown_search: ^5.0.6
  firebase_auth: ^5.1.2
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.3
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/