// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbHPWH0ibpTf0EZ-4EmmuY_HGHom18U7U',
    appId: '1:830251467767:web:f417937318714b5145e4f2',
    messagingSenderId: '830251467767',
    projectId: 'ada-app-flutter',
    authDomain: 'ada-app-flutter.firebaseapp.com',
    storageBucket: 'ada-app-flutter.appspot.com',
    measurementId: 'G-G8RMKW66EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQeZUDGyeND2tuXC4GKoetLgW7oR2zvU',
    appId: '1:830251467767:android:267306c49c8da02345e4f2',
    messagingSenderId: '830251467767',
    projectId: 'ada-app-flutter',
    storageBucket: 'ada-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25Ge--W6svBIcMKm7tyNzbl1nUozjZwY',
    appId: '1:830251467767:ios:8a6492bb51a5f87945e4f2',
    messagingSenderId: '830251467767',
    projectId: 'ada-app-flutter',
    storageBucket: 'ada-app-flutter.appspot.com',
    iosBundleId: 'com.example.adaAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25Ge--W6svBIcMKm7tyNzbl1nUozjZwY',
    appId: '1:830251467767:ios:8a6492bb51a5f87945e4f2',
    messagingSenderId: '830251467767',
    projectId: 'ada-app-flutter',
    storageBucket: 'ada-app-flutter.appspot.com',
    iosBundleId: 'com.example.adaAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbHPWH0ibpTf0EZ-4EmmuY_HGHom18U7U',
    appId: '1:830251467767:web:51313ac0037b84e145e4f2',
    messagingSenderId: '830251467767',
    projectId: 'ada-app-flutter',
    authDomain: 'ada-app-flutter.firebaseapp.com',
    storageBucket: 'ada-app-flutter.appspot.com',
    measurementId: 'G-2WEW58MLSK',
  );

}